name: CI
on:
  # push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: oryd/sdk:v0.0.50
    strategy:
      matrix:
        language: ["golang", "typescript"] # TODO: add the other languages
        client: ["client", "keto", "oathkeeper"] # TODO: add the other clients
    steps:
      - uses: actions/checkout@v3
        # TODO: add version information here?
      - name: Generate ${{ matrix.client }} client for ${{ matrix.language }}
        run: ./scripts/generate.sh ${{ matrix.language }} latest ${{ matrix.client }}
      - name: Test ${{ matrix.client }} client for ${{ matrix.language }}
        run: ./scripts/test.sh ${{ matrix.language }} latest ${{ matrix.client }}
