name: CI
on:
  # push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: oryd/sdk:v0.0.50
    strategy:
      matrix:
        language: ["golang", "typescript"] # TODO: add the other languages
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdk-build-and-test
        with:
          project: client
          language: ${{ matrix.language }}
      - uses: ./.github/actions/sdk-build-and-test
        with:
          project: keto
          language: ${{ matrix.language }}
      - uses: ./.github/actions/sdk-build-and-test
        with:
          project: kratos
          language: ${{ matrix.language }}
      - uses: ./.github/actions/sdk-build-and-test
        with:
          project: hydra
          language: ${{ matrix.language }}
      - uses: ./.github/actions/sdk-build-and-test
        with:
          project: oathkeeper
          language: ${{ matrix.language }}
