name: CI
on:
  # push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: oryd/sdk:v0.0.50
    strategy:
      matrix:
        language: ["golang", "typescript"] # TODO: add the other languages
    steps:
      - uses: actions/checkout@v3
      - name: "client"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest client
      - name: "keto"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest keto
      - name: "kratos"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest kratos
      - name: "hydra"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest hydra
      - name: "oathkeeper"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest oathkeeper
